# Generated by Django 4.1.1 on 2022-11-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_uni', models.CharField(max_length=9, verbose_name='Código UNI')),
                ('numero_dni', models.CharField(max_length=9, verbose_name='Número de DNI')),
                ('apellido_p', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres')),
            ],
            options={
                'verbose_name': 'Alumno',
                'db_table': 'Alumnos',
                'ordering': ['apellido_p', 'apellido_m', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=1, verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Aula',
                'db_table': 'Aulas',
                'ordering': ['aula'],
            },
        ),
        migrations.CreateModel(
            name='CiclosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.CharField(max_length=4, verbose_name='Año')),
                ('ciclo', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Ciclo')),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('V', 'Vacacional')], max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'CiclosAcademico',
                'db_table': 'CiclosAcademicos',
                'ordering': ['anno', 'ciclo'],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prediccion', models.CharField(default='1', max_length=1, verbose_name='Código de Predicción')),
                ('descripcion_prediccion', models.CharField(max_length=10, verbose_name='Descripción de Predicción')),
            ],
            options={
                'verbose_name': 'ClasificacionPrediccion',
                'db_table': 'ClasificacionPrediccion',
                'ordering': ['codigo_prediccion'],
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_dni', models.CharField(max_length=9, verbose_name='Número de DNI')),
                ('apellido_p', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres')),
            ],
            options={
                'verbose_name': 'Docente',
                'db_table': 'Docentes',
                'ordering': ['apellido_p', 'apellido_m', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=1, verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Sección',
                'db_table': 'Secciones',
                'ordering': ['seccion'],
            },
        ),
        migrations.CreateModel(
            name='SistemaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_evaluacion', models.CharField(max_length=1, null=True, verbose_name='Sist. de Evaluación')),
            ],
            options={
                'verbose_name': 'SistemaEvaluacion',
                'db_table': 'SistemasEvaluacion',
                'ordering': ['sistema_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(choices=[('1', 'FIIS'), ('2', 'FIEE'), ('3', 'FIM'), ('4', 'FIA'), ('5', 'FIC'), ('6', 'FIGMM'), ('7', 'FA'), ('8', 'FIECS')], max_length=1, verbose_name='Facultad')),
                ('max_cred', models.IntegerField(verbose_name='Cantidad de Créditos máx. a inscribir')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academico.ciclosacademicos', verbose_name='Ciclo Académico')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academico.alumnos', verbose_name='Alumno')),
                ('id_codigo_prediccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academico.clasificacionprediccion', verbose_name='Código de Predicción')),
            ],
            options={
                'verbose_name': 'Matricula',
                'db_table': 'Matriculas',
                'ordering': ['id_alumno__apellido_p', 'id_alumno__apellido_m'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetido', models.IntegerField(verbose_name='Repetido')),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academico.secciones', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'DetalleMatricula',
                'db_table': 'DetalleMatricula',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código del Curso')),
                ('curso', models.CharField(max_length=40, verbose_name='Curso')),
                ('ciclo', models.CharField(max_length=1, verbose_name='Ciclo')),
                ('creditos', models.IntegerField(verbose_name='Créditos')),
                ('pre_requisitos', models.CharField(max_length=20, null=True, verbose_name='Pre-requisitos')),
                ('sistema_evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.sistemaevaluacion', verbose_name='Sist. de Evaluación')),
            ],
            options={
                'verbose_name': 'Curso',
                'db_table': 'Cursos',
                'ordering': ['curso', 'codigo'],
            },
        ),
    ]
