# Generated by Django 4.1.1 on 2022-11-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallematricula',
            options={'ordering': ['id_curso__curso'], 'verbose_name': 'DetalleMatricula'},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='id_codigo_prediccion',
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='id_codigo_prediccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.clasificacionprediccion', verbose_name='Código de Predicción'),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='id_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.cursos', verbose_name='Curso'),
        ),
    ]
