# Generated by Django 4.1.1 on 2022-11-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_detallematricula_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos', verbose_name='Alumno'),
        ),
    ]
