# Generated by Django 4.1.1 on 2022-11-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_remove_matricula_id_alumno_delete_detallematricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(choices=[('1', 'FIIS'), ('2', 'FIEE'), ('3', 'FIM'), ('4', 'FIA'), ('5', 'FIC'), ('6', 'FIGMM'), ('7', 'FA'), ('8', 'FIECS')], max_length=1, verbose_name='Facultad')),
                ('max_cred', models.IntegerField(verbose_name='Cantidad de Créditos máx. a inscribir')),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='academico.alumnos', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Matricula',
                'db_table': 'Matriculas',
                'ordering': ['id_alumno__apellido_p', 'id_alumno__apellido_m'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetido', models.IntegerField(verbose_name='Repetido')),
                ('id_codigo_prediccion', models.ForeignKey(db_column='id_codigo_prediccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.clasificacionprediccion', verbose_name='Código de Predicción')),
                ('id_curso', models.ForeignKey(db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.cursos', verbose_name='Curso')),
                ('id_seccion', models.ForeignKey(db_column='id_seccion', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.secciones', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'DetalleMatricula',
                'db_table': 'DetalleMatricula',
                'ordering': ['id_curso__curso'],
            },
        ),
    ]
