# Generated by Django 4.1.1 on 2022-11-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_matricula_detallematricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='sistema_evaluacion',
            field=models.ForeignKey(db_column='id_sistema_evaluacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.sistemaevaluacion', verbose_name='Sist. de Evaluación'),
        ),
    ]
