# Generated by Django 4.1.1 on 2022-11-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_alter_cursos_sistema_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_clase', models.CharField(choices=[('T', 'Teórica'), ('P', 'Práctica'), ('Lab', 'Laboratorio')], max_length=3, verbose_name='Tipo de Clase')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábados')], max_length=2, verbose_name='Día')),
                ('hora_ini', models.PositiveSmallIntegerField(verbose_name='Hora Inicial')),
                ('hora_fin', models.PositiveSmallIntegerField(verbose_name='Hora Final')),
                ('vacantes', models.PositiveSmallIntegerField(verbose_name='Vancates')),
                ('inscritos', models.PositiveSmallIntegerField(verbose_name='Inscritos')),
                ('id_aula', models.ForeignKey(db_column='id_aula', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.aulas', verbose_name='Aula')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='academico.cursos', verbose_name='Curso')),
                ('id_docente', models.ForeignKey(db_column='id_docente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docentes', verbose_name='Docente')),
                ('id_seccion', models.ForeignKey(db_column='id_seccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.secciones', verbose_name='Sección')),
            ],
        ),
    ]
