# Generated by Django 4.1.1 on 2022-11-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_cursoseccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoseccion',
            options={'ordering': ['id_curso__curso'], 'verbose_name': 'CursosSeccion'},
        ),
        migrations.AlterModelTable(
            name='cursoseccion',
            table='CursoSeccion',
        ),
    ]
