# Generated by Django 4.1.1 on 2022-11-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_alter_cursoseccion_options_alter_cursoseccion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionprediccion',
            name='codigo_prediccion',
            field=models.CharField(max_length=1, verbose_name='Código de Predicción'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='creditos',
            field=models.PositiveSmallIntegerField(verbose_name='Créditos'),
        ),
        migrations.AlterField(
            model_name='detallematricula',
            name='repetido',
            field=models.PositiveSmallIntegerField(verbose_name='Repetido'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='max_cred',
            field=models.PositiveSmallIntegerField(verbose_name='Cantidad de Créditos máx. a inscribir'),
        ),
    ]
