# Generated by Django 4.1.1 on 2022-11-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_clasificacionprediccion_codigo_prediccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallematricula',
            name='id_matricula',
            field=models.ForeignKey(db_column='id_matricula', default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.matricula', verbose_name='Detalle de Matrícula'),
            preserve_default=False,
        ),
    ]
