# Generated by Django 4.1.1 on 2022-11-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_detallematricula_id_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallematricula',
            name='id_seccion',
            field=models.ForeignKey(db_column='id_seccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.secciones', verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='detallematricula',
            name='repetido',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Repetido'),
        ),
    ]
