# Generated by Django 4.1.1 on 2022-11-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_detallematricula_id_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallematricula',
            name='id_seccion',
            field=models.ForeignKey(blank=True, db_column='id_seccion', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.secciones', verbose_name='Sección'),
        ),
    ]
